//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        public int talento_humano_jefe { get; set; }
        public int talento_humano_empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipo_dia_id { get; set; }
    
        public virtual TipoDia tbl_tipo_dia { get; set; }
        public virtual Usuarios tbl_usuarios { get; set; }
        public virtual Usuarios tbl_usuarios1 { get; set; }
    }
}
