//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.tbl_jerarquia = new HashSet<Jerarquia>();
            this.tbl_usuarios = new HashSet<Usuarios>();
        }
    
        public int departamentoid { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Jerarquia> tbl_jerarquia { get; set; }
        public virtual ICollection<Usuarios> tbl_usuarios { get; set; }
    }
}
