//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogVacaciones
    {
        public int logid { get; set; }
        public int vacacionesid { get; set; }
        public int th_modifico { get; set; }
        public Nullable<int> estatus_anterior { get; set; }
        public int estatus_actual { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Estatus tbl_estatus { get; set; }
        public virtual Estatus tbl_estatus1 { get; set; }
        public virtual Usuarios tbl_usuarios { get; set; }
        public virtual Vacaciones tbl_vacaciones { get; set; }
    }
}
