//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.tbl_permisos = new HashSet<Permisos>();
            this.tbl_usuarios = new HashSet<Usuarios>();
        }
    
        public int rolesid { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Permisos> tbl_permisos { get; set; }
        public virtual ICollection<Usuarios> tbl_usuarios { get; set; }
    }
}
