//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDia
    {
        public TipoDia()
        {
            this.tbl_calendario = new HashSet<Calendario>();
        }
    
        public int tipo_dia_id { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Calendario> tbl_calendario { get; set; }
    }
}
