//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public Vacaciones()
        {
            this.tbl_log_vacaciones = new HashSet<LogVacaciones>();
        }
    
        public int vacacionesid { get; set; }
        public int talento_humano { get; set; }
        public int year { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public System.DateTime fecha_entrada { get; set; }
        public int dias_solicitados { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public System.DateTime fecha_de_aprobacion { get; set; }
        public int estatusid { get; set; }
    
        public virtual Estatus tbl_estatus { get; set; }
        public virtual ICollection<LogVacaciones> tbl_log_vacaciones { get; set; }
        public virtual Usuarios tbl_usuarios { get; set; }
    }
}
