//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VacationEntities : DbContext
    {
        public VacationEntities()
            : base("name=VacationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Departamento> Departamentoes { get; set; }
        public DbSet<Estatus> Estatus { get; set; }
        public DbSet<Jerarquia> Jerarquias { get; set; }
        public DbSet<LogVacaciones> LogVacaciones { get; set; }
        public DbSet<Permisos> Permisos { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<TipoDia> TipoDias { get; set; }
        public DbSet<Calendario> Calendarios { get; set; }
        public DbSet<Vacaciones> Vacaciones { get; set; }
        public DbSet<Calendario> Calendarios { get; set; }
        public DbSet<TipoDia> TipoDias { get; set; }
    }
}
