//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacation_System.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/Web_Service")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.CalendarMirror[] CalendarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.DepartamentoMirror[] DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.JerarquiaMirror[] JerarquiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.LogVacacionesMirror[] LogVacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.PermisosMirror[] PermisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.RolesMirror[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.StatusMirror[] StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.TipoDiaMirror[] TipoDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.UserMirror UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.VacacionesMirror[] VacacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.CalendarMirror[] Calendar {
            get {
                return this.CalendarField;
            }
            set {
                if ((object.ReferenceEquals(this.CalendarField, value) != true)) {
                    this.CalendarField = value;
                    this.RaisePropertyChanged("Calendar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.DepartamentoMirror[] Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.JerarquiaMirror[] Jerarquias {
            get {
                return this.JerarquiasField;
            }
            set {
                if ((object.ReferenceEquals(this.JerarquiasField, value) != true)) {
                    this.JerarquiasField = value;
                    this.RaisePropertyChanged("Jerarquias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.LogVacacionesMirror[] LogVacaciones {
            get {
                return this.LogVacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.LogVacacionesField, value) != true)) {
                    this.LogVacacionesField = value;
                    this.RaisePropertyChanged("LogVacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.PermisosMirror[] Permisos {
            get {
                return this.PermisosField;
            }
            set {
                if ((object.ReferenceEquals(this.PermisosField, value) != true)) {
                    this.PermisosField = value;
                    this.RaisePropertyChanged("Permisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.RolesMirror[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.StatusMirror[] Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.TipoDiaMirror[] TipoDia {
            get {
                return this.TipoDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDiaField, value) != true)) {
                    this.TipoDiaField = value;
                    this.RaisePropertyChanged("TipoDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.UserMirror User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.VacacionesMirror[] Vacaciones {
            get {
                return this.VacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.VacacionesField, value) != true)) {
                    this.VacacionesField = value;
                    this.RaisePropertyChanged("Vacaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class UserMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TalentoHumanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TalentoHumano {
            get {
                return this.TalentoHumanoField;
            }
            set {
                if ((this.TalentoHumanoField.Equals(value) != true)) {
                    this.TalentoHumanoField = value;
                    this.RaisePropertyChanged("TalentoHumano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalendarMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class CalendarMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TalentoHumanoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TalentoHumanoJefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDiaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TalentoHumanoEmpleado {
            get {
                return this.TalentoHumanoEmpleadoField;
            }
            set {
                if ((this.TalentoHumanoEmpleadoField.Equals(value) != true)) {
                    this.TalentoHumanoEmpleadoField = value;
                    this.RaisePropertyChanged("TalentoHumanoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TalentoHumanoJefe {
            get {
                return this.TalentoHumanoJefeField;
            }
            set {
                if ((this.TalentoHumanoJefeField.Equals(value) != true)) {
                    this.TalentoHumanoJefeField = value;
                    this.RaisePropertyChanged("TalentoHumanoJefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDiaId {
            get {
                return this.TipoDiaIdField;
            }
            set {
                if ((this.TipoDiaIdField.Equals(value) != true)) {
                    this.TipoDiaIdField = value;
                    this.RaisePropertyChanged("TipoDiaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartamentoMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class DepartamentoMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((this.DepartamentoIdField.Equals(value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JerarquiaMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class JerarquiaMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JefeTalentoHumanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JerarquiaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TalentoHumanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((this.DepartamentoIdField.Equals(value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JefeTalentoHumano {
            get {
                return this.JefeTalentoHumanoField;
            }
            set {
                if ((this.JefeTalentoHumanoField.Equals(value) != true)) {
                    this.JefeTalentoHumanoField = value;
                    this.RaisePropertyChanged("JefeTalentoHumano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JerarquiaId {
            get {
                return this.JerarquiaIdField;
            }
            set {
                if ((this.JerarquiaIdField.Equals(value) != true)) {
                    this.JerarquiaIdField = value;
                    this.RaisePropertyChanged("JerarquiaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TalentoHumano {
            get {
                return this.TalentoHumanoField;
            }
            set {
                if ((this.TalentoHumanoField.Equals(value) != true)) {
                    this.TalentoHumanoField = value;
                    this.RaisePropertyChanged("TalentoHumano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogVacacionesMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class LogVacacionesMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusAnteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VacacionesIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstatusActual {
            get {
                return this.EstatusActualField;
            }
            set {
                if ((this.EstatusActualField.Equals(value) != true)) {
                    this.EstatusActualField = value;
                    this.RaisePropertyChanged("EstatusActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstatusAnterior {
            get {
                return this.EstatusAnteriorField;
            }
            set {
                if ((this.EstatusAnteriorField.Equals(value) != true)) {
                    this.EstatusAnteriorField = value;
                    this.RaisePropertyChanged("EstatusAnterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Modifico {
            get {
                return this.ModificoField;
            }
            set {
                if ((this.ModificoField.Equals(value) != true)) {
                    this.ModificoField = value;
                    this.RaisePropertyChanged("Modifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VacacionesId {
            get {
                return this.VacacionesIdField;
            }
            set {
                if ((this.VacacionesIdField.Equals(value) != true)) {
                    this.VacacionesIdField = value;
                    this.RaisePropertyChanged("VacacionesId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermisosMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class PermisosMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PermisosIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PermisosId {
            get {
                return this.PermisosIdField;
            }
            set {
                if ((this.PermisosIdField.Equals(value) != true)) {
                    this.PermisosIdField = value;
                    this.RaisePropertyChanged("PermisosId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolesMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class RolesMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vacation_System.ServiceReference.PermisosMirror[] PermisosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vacation_System.ServiceReference.PermisosMirror[] Permisos {
            get {
                return this.PermisosField;
            }
            set {
                if ((object.ReferenceEquals(this.PermisosField, value) != true)) {
                    this.PermisosField = value;
                    this.RaisePropertyChanged("Permisos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class StatusMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDiaMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class TipoDiaMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDiaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((this.DescripcionField.Equals(value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDiaId {
            get {
                return this.TipoDiaIdField;
            }
            set {
                if ((this.TipoDiaIdField.Equals(value) != true)) {
                    this.TipoDiaIdField = value;
                    this.RaisePropertyChanged("TipoDiaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacacionesMirror", Namespace="http://schemas.datacontract.org/2004/07/Web_Service.Mirror_Classes")]
    [System.SerializableAttribute()]
    public partial class VacacionesMirror : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasSolicitadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FechaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TalentoHumanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VacacionesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasSolicitados {
            get {
                return this.DiasSolicitadosField;
            }
            set {
                if ((this.DiasSolicitadosField.Equals(value) != true)) {
                    this.DiasSolicitadosField = value;
                    this.RaisePropertyChanged("DiasSolicitados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstatusId {
            get {
                return this.EstatusIdField;
            }
            set {
                if ((this.EstatusIdField.Equals(value) != true)) {
                    this.EstatusIdField = value;
                    this.RaisePropertyChanged("EstatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAprobacion {
            get {
                return this.FechaAprobacionField;
            }
            set {
                if ((this.FechaAprobacionField.Equals(value) != true)) {
                    this.FechaAprobacionField = value;
                    this.RaisePropertyChanged("FechaAprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrada {
            get {
                return this.FechaEntradaField;
            }
            set {
                if ((this.FechaEntradaField.Equals(value) != true)) {
                    this.FechaEntradaField = value;
                    this.RaisePropertyChanged("FechaEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TalentoHumano {
            get {
                return this.TalentoHumanoField;
            }
            set {
                if ((this.TalentoHumanoField.Equals(value) != true)) {
                    this.TalentoHumanoField = value;
                    this.RaisePropertyChanged("TalentoHumano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VacacionesId {
            get {
                return this.VacacionesIdField;
            }
            set {
                if ((this.VacacionesIdField.Equals(value) != true)) {
                    this.VacacionesIdField = value;
                    this.RaisePropertyChanged("VacacionesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogIn", ReplyAction="http://tempuri.org/IService/LogInResponse")]
        Vacation_System.ServiceReference.Empleado LogIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogIn", ReplyAction="http://tempuri.org/IService/LogInResponse")]
        System.Threading.Tasks.Task<Vacation_System.ServiceReference.Empleado> LogInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        void CreateUser(Vacation_System.ServiceReference.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(Vacation_System.ServiceReference.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateDepartment", ReplyAction="http://tempuri.org/IService/CreateDepartmentResponse")]
        void CreateDepartment(Vacation_System.ServiceReference.DepartamentoMirror depto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateDepartment", ReplyAction="http://tempuri.org/IService/CreateDepartmentResponse")]
        System.Threading.Tasks.Task CreateDepartmentAsync(Vacation_System.ServiceReference.DepartamentoMirror depto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateRol", ReplyAction="http://tempuri.org/IService/CreateRolResponse")]
        void CreateRol(Vacation_System.ServiceReference.RolesMirror rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateRol", ReplyAction="http://tempuri.org/IService/CreateRolResponse")]
        System.Threading.Tasks.Task CreateRolAsync(Vacation_System.ServiceReference.RolesMirror rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadDepartments", ReplyAction="http://tempuri.org/IService/LoadDepartmentsResponse")]
        Vacation_System.ServiceReference.DepartamentoMirror[] LoadDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadDepartments", ReplyAction="http://tempuri.org/IService/LoadDepartmentsResponse")]
        System.Threading.Tasks.Task<Vacation_System.ServiceReference.DepartamentoMirror[]> LoadDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadRoles", ReplyAction="http://tempuri.org/IService/LoadRolesResponse")]
        Vacation_System.ServiceReference.RolesMirror[] LoadRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadRoles", ReplyAction="http://tempuri.org/IService/LoadRolesResponse")]
        System.Threading.Tasks.Task<Vacation_System.ServiceReference.RolesMirror[]> LoadRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadPermisosData", ReplyAction="http://tempuri.org/IService/LoadPermisosDataResponse")]
        string[] LoadPermisosData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadPermisosData", ReplyAction="http://tempuri.org/IService/LoadPermisosDataResponse")]
        System.Threading.Tasks.Task<string[]> LoadPermisosDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveRoleChanges", ReplyAction="http://tempuri.org/IService/SaveRoleChangesResponse")]
        void SaveRoleChanges(Vacation_System.ServiceReference.RolesMirror rolMirror);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveRoleChanges", ReplyAction="http://tempuri.org/IService/SaveRoleChangesResponse")]
        System.Threading.Tasks.Task SaveRoleChangesAsync(Vacation_System.ServiceReference.RolesMirror rolMirror);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Vacation_System.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Vacation_System.ServiceReference.IService>, Vacation_System.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Vacation_System.ServiceReference.Empleado LogIn(string email, string password) {
            return base.Channel.LogIn(email, password);
        }
        
        public System.Threading.Tasks.Task<Vacation_System.ServiceReference.Empleado> LogInAsync(string email, string password) {
            return base.Channel.LogInAsync(email, password);
        }
        
        public void CreateUser(Vacation_System.ServiceReference.Empleado empleado) {
            base.Channel.CreateUser(empleado);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(Vacation_System.ServiceReference.Empleado empleado) {
            return base.Channel.CreateUserAsync(empleado);
        }
        
        public void CreateDepartment(Vacation_System.ServiceReference.DepartamentoMirror depto) {
            base.Channel.CreateDepartment(depto);
        }
        
        public System.Threading.Tasks.Task CreateDepartmentAsync(Vacation_System.ServiceReference.DepartamentoMirror depto) {
            return base.Channel.CreateDepartmentAsync(depto);
        }
        
        public void CreateRol(Vacation_System.ServiceReference.RolesMirror rol) {
            base.Channel.CreateRol(rol);
        }
        
        public System.Threading.Tasks.Task CreateRolAsync(Vacation_System.ServiceReference.RolesMirror rol) {
            return base.Channel.CreateRolAsync(rol);
        }
        
        public Vacation_System.ServiceReference.DepartamentoMirror[] LoadDepartments() {
            return base.Channel.LoadDepartments();
        }
        
        public System.Threading.Tasks.Task<Vacation_System.ServiceReference.DepartamentoMirror[]> LoadDepartmentsAsync() {
            return base.Channel.LoadDepartmentsAsync();
        }
        
        public Vacation_System.ServiceReference.RolesMirror[] LoadRoles() {
            return base.Channel.LoadRoles();
        }
        
        public System.Threading.Tasks.Task<Vacation_System.ServiceReference.RolesMirror[]> LoadRolesAsync() {
            return base.Channel.LoadRolesAsync();
        }
        
        public string[] LoadPermisosData() {
            return base.Channel.LoadPermisosData();
        }
        
        public System.Threading.Tasks.Task<string[]> LoadPermisosDataAsync() {
            return base.Channel.LoadPermisosDataAsync();
        }
        
        public void SaveRoleChanges(Vacation_System.ServiceReference.RolesMirror rolMirror) {
            base.Channel.SaveRoleChanges(rolMirror);
        }
        
        public System.Threading.Tasks.Task SaveRoleChangesAsync(Vacation_System.ServiceReference.RolesMirror rolMirror) {
            return base.Channel.SaveRoleChangesAsync(rolMirror);
        }
    }
}
